export const words  = [
    {   
        id: 1,
        term: 'Assault',
        upvotes: 40,
        definition: 'a physical attack, e.g. getting punched, kicked, stabbed, etc.',
        brief_description: 'An assault is the act of inflicting physical harm or unwanted physical contact upon a person or, in some specific legal definitions, a threat or attempt to commit such an action. \n\nIt is both a crime and a tort and, therefore, may result in either criminal and/or civil liability. Generally, the common law definition is the same in criminal and tort law.',
    }, 
    {   
        id: 2,
        term: 'administrative law',
        upvotes: 20,
        definition: 'The area of law that concerns government agencies.',
        brief_description: 'An assault is the act of inflicting physical harm or unwanted physical contact upon a person or, in some specific legal definitions, a threat or attempt to commit such an action. \n\nIt is both a crime and a tort and, therefore, may result in either criminal and/or civil liability. Generally, the common law definition is the same in criminal and tort law.',
    }, 
    {   
        id: 3,
        term: 'cause of action',
        upvotes: 0,
        definition: 'The reason for which a plaintiff files a complaint or suit against someone.',
        brief_description: 'This can be negligence, breach of contract, malpractice or defamation, to name a few. A cause of action is divided into elements, and each element must be proved to win the case.',
    }, 
    {   
        id: 4,
        term: 'compensatory damages',
        upvotes: 5,
        definition: 'Damages that are recovered for injury or economic loss.',
        brief_description: "For instance, if someone is injured in a car accident and the party who injures them has to pay compensatory damages, the party at fault must cover cost of things such as the ambulance, doctors’ bills, hospital stays, medicine, physical therapy and lost wages.",
    }, 
    {   
        id: 5,
        term: 'diligence',
        upvotes: 180,
        definition: 'Reasonable care or attention to a matter.',
        brief_description: 'for instance, looking both ways before proceeding after stopping at a stop sign, washing your hands before cooking food in a restaurant or operating in a hospital or checking brakes and other mechanical components on tour buses at regular intervals. Due diligence denotes what a normal, responsible person would do under the same conditions.',
    }, 
    {   
        id: 6,
        term: 'malfeasance',
        upvotes: 10,
        definition: 'Doing something illegal or morally wrong. ',
        brief_description: 'Malfeasance includes dishonesty and abuse of authority.',
    }, 
    {   
        id: 7,
        term: 'provisional remedy',
        upvotes: 13,
        definition: ' A temporary court order to protect someone from further or irreparable damage while further legal action is pending',
        brief_description: 'For example, a temporary restraining order is a provisional remedy to help keep someone safe until a hearing to decide if a permanent restraining order is needed; likewise, a temporary injunction to stop the destruction of a building can keep it from being destroyed while the court decides whether it is a landmark.',
    }, 
    {   
        id: 8,
        term: 'stare decisis',
        upvotes: 19,
        definition: 'Latin for “to stand by things decided,” to adhere to precedents of earlier cases as sources of law. ',
        brief_description: ' When an issue has already been ruled upon by a court, other cases involving the same issue must receive the same response from that court or lower courts.',
    }, 
    {   
        id: 9,
        term: 'statute',
        upvotes: 20,
        definition: 'A written law passed by Congress or another legislative body.',
        brief_description: 'A written law passed by Congress or another legislative body.',
    }, 
    {   
        id: 10,
        term: 'tort',
        upvotes: 22,
        definition: 'From the French word for “wrong,” a tort is a wrongful or illegal act, whether intentional or accidental, in which an injury occurs to another.',
        brief_description: 'An intentional tort may also be a crime, such as battery, fraud or theft. Tort law is one of the largest areas of civil law.',
    }, 
    {   
        id: 11,
        term: 'wobbler',
        upvotes: 20,
        definition: 'a wobbler is a crime that can be classified as either a felony or a misdemeanor. ',
        brief_description: 'In some states, even if an offender is charged with a felony in a wobbler case, the judge may have the authority to reduce the conviction to a misdemeanor.',
    }, 

]